apiVersion: v1
appVersion: 2.28.4
description: A Helm chart to deploy aws-for-fluent-bit project
home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
keywords:
- eks
- fluentbit
- fluent-bit
- cloudwatch
- firehose
- kinesis
maintainers:
- email: mforutan@users.noreply.github.com
  name: Mohammad Forutan
  url: https://github.com/mforutan
name: aws-for-fluent-bit
sources:
- https://github.com/aws/eks-charts
version: 0.1.24
